name: goodreads
version: '3.9'


services:
  app:
    container_name: app
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate
      && gunicorn --workers=3 --timeout=600 --bind=0.0.0.0:8000 config.wsgi:application"
    depends_on:
      - postgres
    env_file:
      - .compose/config.env
    networks:
      - goodreads
    ports:
      - "8000:8000"
    restart: always


  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goodreads
    networks:
      - goodreads
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data


networks:
  goodreads:
    driver: bridge

volumes:
  postgres-data: